routes/web.php
<?php

Auth::routes();

Route::middleware('auth')
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('home.default');
        Route::get('/home', 'DashboardController@index')->name('home');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('lang/{locale}', 'DashboardController@lang')->name('lang.set-locale');
    });


Route::namespace('Company')
    ->middleware('auth')
    ->group(function () {
        Route::resource('company', 'CompanyController');
    });

Route::namespace('Employee')
    ->middleware('auth')
    ->group(function () {
        Route::resource('employee', 'EmployeeController');
    });

app/Models/Employee.php
<?php

namespace App\Models;

use App\Models\Company;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $hidden = [
        'created_at', 'updated_at'
    ];

    protected $guarded = [
        'id'
    ];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/Employee/EmployeeController.php
<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmployeeRequest;
use App\Interfaces\EmployeeRepositoryInterface;
use App\Interfaces\CompanyRepositoryInterface;

class EmployeeController extends Controller
{
    public function __construct(EmployeeRepositoryInterface $employee, CompanyRepositoryInterface $company)
    {
        $this->employee = $employee;
        $this->company = $company;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'title' => trans('sentence.employee').' - '.trans('sentence.listing'),
            'employees' => $this->employee->all()
        ];

        return view('employee.listing', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => trans('sentence.employee').' - '.trans('sentence.create'),
            'companies' => $this->company->all(),
        ];

        return view('employee.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Backend\EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $this->employee->create($request);

        return redirect()->route('employee.index')->with('success', 'Employee created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'title' => trans('sentence.employee').' - '.trans('sentence.view'),
            'employee' => $this->employee->show($id)
        ];

        return view('employee.view', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'title' => trans('sentence.employee').' - '.trans('sentence.edit'),
            'companies' => $this->company->all(),
            'employee' => $this->employee->show($id),
        ];

        return view('employee.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Backend\EmployeeRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, $id)
    {
        $this->employee->update($request, $id);

        return redirect()->back()->with('success', 'Employee updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->employee->destroy($id);

        return redirect()->back()->with('success', 'Employee deleted successfully');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.app') @section('content')
<div class="row">
    <div class="col-12">
        <form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data" class="addEditEmployee">
            @csrf
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            {{ trans('sentence.create').' - '.trans('sentence.employee') }}
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>{{ trans('sentence.first').' '.trans('sentence.name') }}:</label>
                        <input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.last').' '.trans('sentence.name') }}:</label>
                        <input class="form-control" type="last_name" name="last_name" value="{{ old('last_name') }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.company') }}:</label>
                        <select name="company" class="form-control">
                            <option value="select">{{ trans('sentence.select').' '.trans('sentence.company') }}</option>
                            @foreach ($companies as $company)
                        <option value="{{ $company->id }}" {{ $company->id == old('company') ? "selected" : "" }}> {{ $company->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.email') }}:</label>
                        <input class="form-control" type="text" name="email" value="{{ old('email') }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.phone') }}:</label>
                        <input class="form-control" type="text" name="phone" value="{{ old('phone') }}">
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">{{ trans('sentence.create') }}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app') @section('content')
<div class="row">
    <div class="col-12">
        <form action="{{ route('employee.update', $employee->id) }}" method="post" enctype="multipart/form-data" class="addEditEmployee">
            @method('PATCH')
            @csrf
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            {{ trans('sentence.edit').' - '.trans('sentence.employee') }}
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>{{ trans('sentence.first').' '.trans('sentence.name') }}:</label>
                        <input class="form-control" type="text" name="first_name" value="{{ old('first_name') ?? $employee->first_name }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.last').' '.trans('sentence.name') }}:</label>
                        <input class="form-control" type="last_name" name="last_name" value="{{ old('last_name') ?? $employee->last_name }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.company') }}:</label>
                        <select name="company" class="form-control">
                            <option value="select">Select Company</option>
                            @foreach ($companies as $company)
                        <option value="{{ $company->id }}" {{ $company->id == old('company') ? "selected" : ( $company->id == $employee->company_id ? "selected" : "" ) }}> {{ $company->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.email') }}:</label>
                        <input class="form-control" type="text" name="email" value="{{ old('email') ?? $employee->email }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.phone') }}:</label>
                        <input class="form-control" type="text" name="phone" value="{{ old('phone') ?? $employee->phone }}">
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">{{ trans('sentence.update') }}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/employee/listing.blade.php
@extends('layouts.app') @section('content')
<div class="row">
    <div class="col-12">
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        {{ trans('sentence.employees') }}
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">

                <!--begin::Section-->
                <div class="kt-section">
                    <div class="kt-section__content">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <th>#</th>
                                    <th>{{ trans('sentence.first').' '.trans('sentence.name') }}</th>
                                    <th>{{ trans('sentence.last').' '.trans('sentence.name') }}</th>
                                    <th>{{ trans('sentence.company') }}</th>
                                    <th>{{ trans('sentence.email') }}</th>
                                    <th>{{ trans('sentence.phone') }}</th>
                                    <th>{{ trans('sentence.actions') }}</th>
                                </thead>
                                <tbody>
                                    @foreach ($employees as $i => $employee)
                                    <tr>
                                        <th>{{ $i + $employees->firstItem() }}</th>
                                        <td>{{ $employee->first_name }}</td>
                                        <td>{{ $employee->last_name }}</td>
                                        <td><a href="{{ route('company.show', $employee->company->id) }}">{{ $employee->company->name }}</a></td>
                                        <td>{{ $employee->email }}</td>
                                        <td>{{ $employee->phone }}</td>
                                        <td>
                                            <a href="{{ route('employee.show', $employee->id) }}" class="btn btn-info btn-sm btn-elevate btn-circle btn-icon"><span class="flaticon-eye"></span></a>
                                            <a href="{{ route('employee.edit', $employee->id) }}" class="btn btn-warning btn-sm btn-elevate btn-circle btn-icon"><span class="flaticon-edit"></span></a>
                                            <form action="{{ route('employee.destroy', $employee->id) }}" method="post" class="d-inline-block">
                                                @csrf @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm btn-elevate btn-circle btn-icon"><span class="flaticon-delete"></span></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $employees->links() }}
                        </div>
                    </div>
                </div>

                <!--end::Section-->
            </div>

        </div>
    </div>
</div>
@endsection @section('toolbar')
<a href="{{ route('employee.create') }}" class="btn btn-success btn-elevate btn-circle btn-icon" data-toggle="kt-tooltip" data-container="body" data-placement="bottom" title="" data-original-title="{{ trans('sentence.add').' '.trans('sentence.employee') }}"><i class="flaticon2-plus"></i></a> @endsection

resources/views/employee/view.blade.php
@extends('layouts.app') @section('content')
<div class="row">
    <div class="col-12">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            {{ trans('sentence.view').' - '.trans('sentence.employee') }}
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>{{ trans('sentence.first').' '.trans('sentence.name') }}:</label>
                        <input class="form-control" type="text" name="first_name" value="{{ $employee->first_name }}" readonly>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.last').' '.trans('sentence.name') }}:</label>
                        <input class="form-control" type="last_name" name="last_name" value="{{ $employee->last_name }}" readonly>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.company') }}:</label>
                        <input class="form-control" type="company" name="company" value="{{ $employee->company->name }}" readonly>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.email') }}:</label>
                        <input class="form-control" type="text" name="email" value="{{ $employee->email }}" readonly>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.phone') }}:</label>
                        <input class="form-control" type="text" name="phone" value="{{ $employee->phone }}" readonly>
                    </div>
                </div>
            </div>
    </div>
</div>
@endsection