routes/web.php
<?php

Auth::routes();

Route::middleware('auth')
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('home.default');
        Route::get('/home', 'DashboardController@index')->name('home');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('lang/{locale}', 'DashboardController@lang')->name('lang.set-locale');
    });


Route::namespace('Company')
    ->middleware('auth')
    ->group(function () {
        Route::resource('company', 'CompanyController');
    });

Route::namespace('Employee')
    ->middleware('auth')
    ->group(function () {
        Route::resource('employee', 'EmployeeController');
    });

app/Models/Company.php
<?php

namespace App\Models;

use App\Models\Employee;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $hidden = [
        'created_at', 'updated_at'
    ];

    protected $guarded = [
        'id'
    ];

    public function user()
    {
        return $this->hasMany(Employee::class);
    }
}

app/Http/Controllers/Company/CompanyController.php
<?php

namespace App\Http\Controllers\Company;

use App\Http\Controllers\Controller;
use App\Interfaces\CompanyRepositoryInterface;
use App\Http\Requests\CompanyRequest;

class CompanyController extends Controller
{
    public function __construct(CompanyRepositoryInterface $company)
    {
        $this->company = $company;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'title' => trans('sentence.company').' - '.trans('sentence.listing'),
            'companies' => $this->company->all(true)
        ];

        return view('company.listing', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'title' => trans('sentence.company').' - '.trans('sentence.view'),
            'company' => $this->company->show($id)
        ];

        return view('company.view', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => trans('sentence.company').' - '.trans('sentence.create'),
        ];

        return view('company.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Backend\CompanyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        $this->company->create($request);

        return redirect()->route('company.index')->with('success', 'Company created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'title' => trans('sentence.company').' - '.trans('sentence.edit'),
            'company' => $this->company->show($id),
        ];

        return view('company.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Backend\CompanyRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, $id)
    {
        $this->company->update($request, $id);

        return redirect()->route('company.index')->with('success', 'Company updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->company->destroy($id);

        return redirect()->back()->with('success', 'Company deleted successfully');
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-12">
            <form action="{{ route('company.store') }}" method="post" enctype="multipart/form-data" class="addEditCompany">
            @csrf
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                           {{ trans('sentence.create')." ".trans('sentence.company') }}
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>{{ trans('sentence.name') }}:</label>
                        <input class="form-control" type="text" name="name" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.email') }}:</label>
                        <input class="form-control" type="email" name="email" value="{{ old('email') }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.logo') }}:</label>
                        <div class="thumb-container">
                        <img src="http://via.placeholder.com/350x350.jpg"  class="img-fluid actualthumb" alt="">
                        <button type="button" class="btn btn-primary  btn-sm btn-icon btn-circle" onclick="showPicker('.thumbnaihiddenpicker')"><i class="flaticon-edit"></i></button>
                        </div>
                        <div class="position-relative">
                        <input type="file" accept="image/png, image/jpeg, image/jpg"  name="logo" class="thumbnaihiddenpicker">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.website') }}:</label>
                        <input class="form-control" type="text" name="website" value="{{ old('website') }}">
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                    <button type="submit" class="btn btn-primary">{{ trans('sentence.create') }}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app') @section('content')
<div class="row">
    <div class="col-12">
        <!--begin::Portlet-->
        <form action="{{ route('company.update', $company->id) }}" method="post" enctype="multipart/form-data" class="addEditCustomer">
            @csrf @method('PATCH')
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            {{ trans('sentence.edit')." ".trans('sentence.company') }}
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>{{ trans('sentence.name') }}:</label>
                        <input class="form-control" type="text" name="name" value="{{ old('name') ?? $company->name }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.email') }}:</label>
                        <input class="form-control" type="email" name="email" value="{{ old('email') ?? $company->email }}">
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.logo') }}:</label>
                        <div class="thumb-container">
                            <img src="{{ asset('public/storage/'.$company->logo) }}" class="img-fluid actualthumb" alt="">
                            <button type="button" class="btn btn-primary  btn-sm btn-icon btn-circle" onclick="showPicker('.thumbnaihiddenpicker')"><i class="flaticon-edit"></i></button>
                        </div>
                        <div class="position-relative">
                            <input type="file" accept="image/png, image/jpeg, image/jpg" name="logo" class="thumbnaihiddenpicker">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>{{ trans('sentence.website') }}:</label>
                        <input type="text" name="website" class="form-control" value="{{ old('website') ?? $company->website }}">
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">{{ trans('sentence.update') }}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/company/listing.blade.php
@extends('layouts.app') @section('content')
<div class="row">
    <div class="col-12">
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Companies
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">

                <!--begin::Section-->
                <div class="kt-section">
                    <div class="kt-section__content">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <th>#</th>
                                    <th>{{ trans('sentence.logo') }}</th>
                                    <th>{{ trans('sentence.name') }}</th>
                                    <th>{{ trans('sentence.email') }}</th>
                                    <th>{{ trans('sentence.actions') }}</th>
                                </thead>
                                <tbody>
                                    @foreach ($companies as $i => $company)
                                    <tr>
                                        <th>{{ $i + $companies->firstItem() }}</th>
                                        <td>
                                            <div class="user-thumbnail-img"><img src="{{ asset("public/storage/".$company->logo) }}" alt="" class="img-fluid"></div>
                                        </td>
                                        <td>{{ $company->name }}</td>
                                        <td>{{ $company->email }}</td>
                                        <td>
                                            <a href="{{ route('company.show', $company->id) }}" class="btn btn-info btn-sm btn-elevate btn-circle btn-icon"><span class="flaticon-eye"></span></a>
                                            <a href="{{ route('company.edit', $company->id) }}" class="btn btn-warning btn-sm btn-elevate btn-circle btn-icon"><span class="flaticon-edit"></span></a>
                                            <form action="{{ route('company.destroy', $company->id) }}" method="post" class="d-inline-block">
                                                @csrf @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm btn-elevate btn-circle btn-icon"><span class="flaticon-delete"></span></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $companies->links() }}

                        </div>
                    </div>
                </div>

                <!--end::Section-->
            </div>

        </div>
    </div>
</div>
@endsection

@section('toolbar')
<a href="{{ route('company.create') }}" class="btn btn-success btn-elevate btn-circle btn-icon" data-toggle="kt-tooltip" data-container="body" data-placement="bottom" title="" data-original-title="{{ trans('sentence.add')." ".trans('sentence.company') }}"><i class="flaticon2-plus"></i></a> 
@endsection

resources/views/company/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-12">
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        {{ trans('sentence.view')." ".trans('sentence.company') }}
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="form-group">
                    <label>{{ trans('sentence.name') }}:</label>
                    <input class="form-control" type="text" name="name" value="{{ $company->name }}" readonly>
                </div>
                <div class="form-group">
                    <label>{{ trans('sentence.email') }}:</label>
                    <input class="form-control" type="email" name="email" value="{{ $company->email }}" readonly>
                </div>
                <div class="form-group">
                    <label>{{ trans('sentence.logo') }}:</label>
                    <div class="thumb-container">
                        <img src="{{ asset('public/storage/'.$company->logo) }}" class="img-fluid actualthumb" alt="">
                    </div>
                </div>
                <div class="form-group">
                    <label>{{ trans('sentence.website') }}:</label>
                    <input class="form-control" type="text" name="website" value="{{ $company->website }}" readonly>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection